services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '${NGINX_PORT:-80}:80'
  #     - '${NGINX_SSL_PORT:-443}:443'
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/certs:/etc/nginx/ssl
  #   depends_on:
  #     - app
  #   networks:
  #     - local_network
  app:
    build: .
    ports:
      - "${PORT:-3333}:3333"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
      - redis
    networks:
      - local_network
  mysql:
    image: mysql
    ports:
      - "3356:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: cashback_app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local_network
  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - local_network
  mailhog:
    image: jcalonso/mailhog:latest
    ports:
      - "${MAIL_PORT:-1025}:1025"
      - "8025:8025"
    networks:
      - local_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - local_network
volumes:
  mysql_data:
  redis_data:
  elasticsearch_data:
networks:
  local_network:
    driver: bridge
